_include_models:
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
calibrated: false
wagering_method:
  name: mse_br_wagers_v2
  config:
    hidden_dim: 4096
    hidden_layers:
    - 512
    - 256
    hidden_state_layers_per_model:
    - -4
    - -3
    - -2
    - -1
    learning_rate: 5e-6
    lr_decay_factor: 1
    lr_decay_steps: 100
    temperature: 2.0
    grad_clip_norm: 1.0
    normalize_hidden_states: false
    device: cuda:0
aggregation:
  name: weighted_linear_pooling
  config: {}
option_tokens:
- '1'
- '0'
_include_datasets:
- datasets/cluster_saturation_bayes_extreme_uniform.yaml
cache_path: /research/projects/ecoai/yl2310/MultiLLMs/cache
num_epochs: 5
checkpoint_base_dir: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints/mse_br_wagers_v2_cluster_saturation_bayesX_mixed_layers/repeat_0000
save_every: 100
training_batch_size: 100
auto_resume: false
balance_training_datasets: true
shuffle_data: true
shuffle_seed: 18
early_stopping_patience: 150
early_stopping_criterion: online_learning
use_brier_d_regret_for_early_stopping: true
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: mse_br_wagers_v2_cluster_saturation_bayesX_mixed_layers
_include_test_datasets:
- datasets/cluster_saturation_bayes_extreme_uniform.yaml
test_datasets:
- display_name: cluster_saturation_bayesX_4
dataset_split_seed: 42
eval_checkpoint_dir: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints/mse_br_wagers_v2_cluster_saturation_bayesX_mixed_layers/repeat_0000/eval
checkpoint_path: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints/mse_br_wagers_v2_cluster_saturation_bayesX_mixed_layers/repeat_0000
